// Generated by Bisonc++ V4.05.00 on Sat, 14 Feb 2015 14:45:53 -0800

#ifndef Parser_h_included
#define Parser_h_included

#include <fstream>
#include "Ir.h"

using namespace Decaf;

// $insert baseclass
#include "Parserbase.h"
// $insert scanner.h
#include "Scanner.h"


#undef Parser
class Parser: public ParserBase
{
    // $insert scannerobject
    Scanner d_scanner;

    IrClass* d_root;
    IrTraversalContext* d_ctx;
    
    std::vector<std::string> d_source;
    std::string d_blank;
    
    public:
        Parser(std::istream &in, std::ostream &out, bool ia64) :
            d_scanner(in, out),
            d_root(0) 
        {
            d_scanner.setSLoc(&d_loc__);
            d_ctx = new IrTraversalContext(ia64);
        }
        Parser(std::string const &infile, std::string const &outfile, bool ia64) :
            d_scanner(infile, outfile),
            d_root(0) 
        {
            preloadSource(infile);            
            d_scanner.setSLoc(&d_loc__);            
            d_ctx = new IrTraversalContext(ia64);
            d_ctx->setSource(&d_source);
        }
        virtual ~Parser() {}
        int parse();
        bool codegen()
        {
            if (d_root)
            {
                d_root->codegen(d_ctx);
                    
                // write string table
                d_ctx->genStrings();
    
                // convert TAC into x86_64 assembly
                d_ctx->codegen(d_scanner.outStream());
            }
            return false;
        }
        void dumpAST() 
        { 
            if (d_root) 
                d_root->print(0); 
        }
        bool semanticChecks() 
        { 
            if (d_root) 
            {
                d_root->propagateTypes(d_ctx);
                return d_root->analyze(d_ctx); 
            }
            return false; 
        }
        
    private:
        void error(char const *msg);    // called on (syntax) errors
        int lex();                      // returns the next token from the
                                        // lexical scanner. 
        void print();                   // use, e.g., d_token, d_loc

        void setRoot(IrClass* root) { d_root = root; }
        
        const std::string& line(size_t line_num) const;
        
        void preloadSource(const std::string &infile);

    // support functions for parse():
        void executeAction(int ruleNr);
        void errorRecovery();
        int lookup(bool recovery);
        void nextToken();
        void print__();
        void exceptionHandler__(std::exception const &exc);
};


#endif
