// Generated by Flexc++ V2.15.00 on Sat, 19 Jul 2025 08:10:53 -0700

#ifndef Scanner_H_INCLUDED_
#define Scanner_H_INCLUDED_

#include <iostream>
#include "Ir.h"

using namespace Decaf;

// $insert baseclass_h
#include "Scannerbase.h"
#include "Parserbase.h"

// $insert classHead
class Scanner: public ScannerBase
{
    public:
        explicit Scanner(std::istream &in = std::cin, std::ostream &out = std::cout, bool keepCwd = true);

        Scanner(std::string const &infile, std::string const &outfile, bool keepCwd = true);
        
        // $insert lexFunctionDecl
        int lex();

        int columnNr() { return m_current_column; }
        
        void setSLoc(ParserBase::LTYPE_ *location) { m_loc = location; }
        
        std::ostream   &outStream() { return out(); }
        
    protected:
    
        int m_current_column;
        
        void error();
        void track_column();

    private:
        int lex_();
        int executeAction_(size_t ruleNr);

        void print();
        void preCode();     // re-implement this function for code that must 
                            // be exec'ed before the patternmatching starts

        void postCode(PostEnum_ type);    
                            // re-implement this function for code that must 
                            // be exec'ed after the rules's actions.
        
        ParserBase::LTYPE_* m_loc;
};

// $insert scannerConstructors
inline Scanner::Scanner(std::istream &in, std::ostream &out, bool keepCwd)
:
    ScannerBase(in, out, keepCwd),
    m_current_column(0),
    m_loc(nullptr)
{}

inline Scanner::Scanner(std::string const &infile, std::string const &outfile, bool keepCwd)
:
    ScannerBase(infile, outfile, keepCwd),
    m_current_column(0),
    m_loc(nullptr)
{}

// $insert inlineLexFunction
inline int Scanner::lex()
{
    return lex_();
}

inline void Scanner::preCode() 
{
    // optionally replace by your own code
}

inline void Scanner::postCode([[maybe_unused]] PostEnum_ type) 
{
    // optionally replace by your own code
}

inline void Scanner::error()
{
    std::cout << filename() << " line " << lineNr() << ":" << columnNr() << ": unexpected char: \'" << matched().front() << "\'" << std::endl; 
}

inline void Scanner::track_column()
{
    const int tab_width = 4;

    m_loc->first_line = lineNr();
    m_loc->first_column = columnNr();
    
    for (auto it = matched().cbegin(); it != matched().cend(); ++it)
    {
        if (*it == '\n')
            m_current_column = 0;
        else if (*it == '\t')
            m_current_column += tab_width - (m_current_column % tab_width);
        else
            m_current_column++;
    }

    m_loc->last_line = lineNr();
    m_loc->last_column = columnNr();    
}

inline void Scanner::print() 
{
    print_();
}


#endif // Scanner_H_INCLUDED_

